### ISSUE TITLE
Failed to locate events database

### ISSUE THREAD

**Issue by sahmad98** [Morgan-Stanley/Xpedite#90]
When trying to run `xpedite metrics`, following error is generated

```
$ xpedite metrics
syncing uarch spec database for 40 micro architectures
        downloading uarch spec for HSW -> completed in 1.99 sec.
        ...
        downloading uarch spec for WSM-EP-SP -> completed in 2.01 sec.
        downloading uarch spec for SNR -> completed in 1.70 sec.Traceback (most recent call last):
  File "/home/saleem.a/source/Xpedite/scripts/bin/xpedite", line 251, in <module>
    app.run()
  File "/home/saleem.a/source/Xpedite/install/runtime/lib/python2.7/site-packages/cement/core/foundation.py", line 797, in run
    return_val = self.controller._dispatch()
  File "/home/saleem.a/source/Xpedite/install/runtime/lib/python2.7/site-packages/cement/ext/ext_argparse.py", line 901, in _dispatch
    return func()
  File "/home/saleem.a/source/Xpedite/scripts/bin/xpedite", line 202, in metrics
    topdown = Topdown(_loadPerfEventsDb())
  File "/home/saleem.a/source/Xpedite/scripts/bin/xpedite", line 43, in _loadPerfEventsDb
    return loadEventsDb(getCpuId())
  File "/home/saleem.a/source/Xpedite/scripts/lib/xpedite/pmu/eventsDb.py", line 138, in loadEventsDb
    'to add support for this architecture'.format(cpuId)
Exception: failed to locate events database file for cpu GenuineIntel-6-05. please consult xpedite devs to add support for this architecture

```

The machine i am currently run is a **i9 skylake server**

```
$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Core(TM) i9-7980XE CPU @ 2.60GHz
```

I can see that skylake map file is there but **GenuineIntel-6-05** family model is not in the [mapfile](https://download.01.org/perfmon/mapfile.csv) .

One thing which can be done to counter this is to read the events in the similar way the **perf** tool reads pmu events.

**Comment by sahmad98** [comment]
I have tried running it on my local machine, which is i5 (ivybridge) following observations i have found 

```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Vendor ID:           GenuineIntel
CPU family:          6
Model:               58
Model name:          Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
```

I am getting the same error
```
Exception: failed to locate events database file for cpu **GenuineIntel-6-0A**. please consult xpedite devs to add support for this architecture
```

But the thing to note is that the **hex** for model number 58 is **0x3A** and i can see a corresponding entry in the map file, while the family name deduced is **GenuineIntel-6-0A** instead of **GenuineIntel-6-3A**

I have tried printing the full cpu info used in the `xpedite` script for my i5 machine and following is the output

```
{
   'count':4,
   'extended_model':3,
   'l2_cache_line_size':6,
   'python_version':'2.7.15.final.0 (64 bit)',
   'family':6,
   'bits':64,
   'brand':'Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz',
   'vendor_id':'GenuineIntel',
   'cpuinfo_version':[ 5, 0,  0 ],
   'raw_arch_string':'x86_64',
   'flags':[      'acpi',      'aes',      'apic',      'avx',      'clflush',      'cmov',      'cx16',      'cx8',      'de',
      'ds_cpl',      'dtes64',      'dts',      'erms',      'est',      'f16c',      'fpu',      'fxsr',      'ht',      'lahf_lm',
      'mca',      'mce',      'mmx',      'monitor',      'msr',      'mtrr',      'osxsave',      'pae',      'pat',      'pbe',
      'pcid',      'pclmulqdq',      'pdcm',      'pge',      'pni',      'popcnt',      'pse',      'pse36',      'rdrnd',
      'sep',      'smep',      'ss',      'sse',      'sse2',      'sse4_1',      'sse4_2',      'ssse3',      'tm',
      'tm2',      'tsc',      'tscdeadline',      'vme',      'vmx',      'x2apic',      'xsave',      'xtpr'
   ],
   'l2_cache_size':'64',
   'l2_cache_associativity':'0x100L',
   'stepping':9,
   'hz_actual_raw':[      2495526619,      0   ],
   'hz_actual':'2.4955 GHz',
   'arch':'X86_64',
   'model':10,
   'hz_advertised_raw':[      2500000000,      0   ],
   'hz_advertised':'2.5000 GHz'
}
```

#### Few Points
* The model returned by the **getCpuInfo()** function is wrong as compared to `lscpu` output.
* The library used by `py-cpuinfo` is returning incorrect information. 
* I have tried running the same command `xpedite list` and getting two different out

#### First Output
```
➜  scripts git:(master) ✗ xpedite list
None
{'count': 4, 'extended_model': 3, 'l2_cache_line_size': 6, 'python_version': '2.7.15.final.0 (64 bit)', 'family': 6, 'bits': 64, 'brand': 'Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz', 'vendor_id': 'GenuineIntel', 'cpuinfo_version': [5, 0, 0], 'raw_arch_string': 'x86_64', 'flags': ['acpi', 'aes', 'apic', 'avx', 'clflush', 'cmov', 'cx16', 'cx8', 'de', 'ds_cpl', 'dtes64', 'dts', 'erms', 'est', 'f16c', 'fpu', 'fxsr', 'ht', 'lahf_lm', 'mca', 'mce', 'mmx', 'monitor', 'msr', 'mtrr', 'osxsave', 'pae', 'pat', 'pbe', 'pcid', 'pclmulqdq', 'pdcm', 'pge', 'pni', 'popcnt', 'pse', 'pse36', 'rdrnd', 'sep', 'smep', 'ss', 'sse', 'sse2', 'sse4_1', 'sse4_2', 'ssse3', 'tm', 'tm2', 'tsc', 'tscdeadline', 'vme', 'vmx', 'x2apic', 'xsave', 'xtpr'], 'l2_cache_size': '64', 'l2_cache_associativity': '0x100L', 'stepping': 9, 'hz_actual_raw': [2495526619, 0], 'hz_actual': '2.4955 GHz', 'arch': 'X86_64', 'model': 10, 'hz_advertised_raw': [2500000000, 0], 'hz_advertised': '2.5000 GHz'}
Traceback (most recent call last):
  File "/home/saleem/source/Xpedite/scripts/bin/xpedite", line 251, in <module>
    app.run()
  File "/home/saleem/source/Xpedite/install/runtime/local/lib/python2.7/site-packages/cement/core/foundation.py", line 797, in run
    return_val = self.controller._dispatch()
  File "/home/saleem/source/Xpedite/install/runtime/local/lib/python2.7/site-packages/cement/ext/ext_argparse.py", line 901, in _dispatch
    return func()
  File "/home/saleem/source/Xpedite/scripts/bin/xpedite", line 194, in list
    eventsDb = _loadPerfEventsDb()
  File "/home/saleem/source/Xpedite/scripts/bin/xpedite", line 43, in _loadPerfEventsDb
    return loadEventsDb(getCpuId())
  File "/home/saleem/source/Xpedite/scripts/lib/xpedite/pmu/eventsDb.py", line 138, in loadEventsDb
    'to add support for this architecture'.format(cpuId)
Exception: failed to locate events database file for cpu GenuineIntel-6-0A. please consult xpedite devs to add support for this architecture
```

#### Second Output
```
➜  scripts git:(master) ✗ xpedite list
None
{'count': 4, 'python_version': '2.7.15.final.0 (64 bit)', 'bits': 64, 'cpuinfo_version': [5, 0, 0], 'raw_arch_string': 'x86_64', 'arch': 'X86_64'}
Traceback (most recent call last):
  File "/home/saleem/source/Xpedite/scripts/bin/xpedite", line 251, in <module>
    app.run()
  File "/home/saleem/source/Xpedite/install/runtime/local/lib/python2.7/site-packages/cement/core/foundation.py", line 797, in run
    return_val = self.controller._dispatch()
  File "/home/saleem/source/Xpedite/install/runtime/local/lib/python2.7/site-packages/cement/ext/ext_argparse.py", line 901, in _dispatch
    return func()
  File "/home/saleem/source/Xpedite/scripts/bin/xpedite", line 194, in list
    eventsDb = _loadPerfEventsDb()
  File "/home/saleem/source/Xpedite/scripts/bin/xpedite", line 43, in _loadPerfEventsDb
    return loadEventsDb(getCpuId())
  File "/home/saleem/source/Xpedite/scripts/lib/xpedite/util/__init__.py", line 218, in getCpuId
    return '{}-{}-{:02X}'.format(cpuInfo['vendor_id'], cpuInfo['family'], cpuInfo['model'])
KeyError: 'vendor_id'
```
